spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level: debug

s3:
  accessKeyId: AKIAJ3U3XXINZDXPPB7A
  secretAccessKey: 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
  bucketName: nev-aws-demo
  region: s3-ap-northeast-1
  folder: img

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/demo_java
    username: demo_java
    password: demo_java

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://mysql-01.c6jx5lsuwgfv.ap-northeast-1.rds.amazonaws.com:3306/demo_java
    username: demo_java
    password: demo_java
