spring:
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level: debug

s3:
  accessKeyId: accessKey
  secretAccessKey: secretKey
  bucketName: vn.khoibv.aws-demo
  region: s3-us-east-1
  folder: img

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/demo_java
    username: demo_java
    password: demo_java

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://mysql-01.cgovit83emuh.us-east-1.rds.amazonaws.com:3306/demo_java
    username: demo_java
    password: demo_java
